/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "ADCINC12.h"
#include "AMUX4_ADC.h"
#include "E2PROM.h"
#include "LCD.h"
#include "PGA_ADC.h"
#include "PGA_DDS_1.h"
#include "PGA_DDS_2.h"
#include "PWM8_BUZZ.h"
#include "UART.h"

#endif
